name: CI
on:
  # Triggers the workflow on push or pull request events
  pull_request:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Tests Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          python-version: 3.7.1
          auto-activate-base: True
      - name: Install Dependencies and pynmfk
        run: |
          conda info
          conda list
          conda install mpi4py
          python setup.py install
          
      - name: Test test_dist_nmf_1d_nnsvd_init 
        run: |
          cd tests && timeout --preserve-status ${TIME_OUT}m mpirun -n 2 python -m pytest test_dist_nmf_1d_nnsvd_init.py --with-mpi
      
      - name: Test test_dist_nmf_2d
        run: |
          cd tests && timeout --preserve-status 1m mpirun -n 2 python -m pytest test_dist_nmf_2d.py --with-mpi
          
      - name: Test test_dist_nmf_1d
        run: |
          cd tests && timeout --preserve-status 1m mpirun -n 2 python -m pytest test_dist_nmf_1d.py --with-mpi
          
      - name: Test test_dist_nnsvd
        run: |
          cd tests && timeout --preserve-status 1m mpirun -n 2 python -m pytest test_dist_nnsvd.py --with-mpi
      
      - name: Test test_dist_clustering
        run: |
          cd tests && timeout --preserve-status 1m mpirun -n 2 python -m pytest test_dist_clustering.py --with-mpi
          
      - name: Test test_dist_file_split
        run: |
          cd tests && timeout --preserve-status 1m mpirun -n 2 python -m pytest test_dist_file_split.py --with-mpi
      
        env:
          OMPI_ALLOW_RUN_AS_ROOT: '1'
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: '1'
          TIME_OUT: 1 
