name: CI
on:
  # Triggers the workflow on push or pull request events
  pull_request:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  test:
    name: Tests Linux
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          python-version: 3.7.1
          auto-activate-base: True
      - name: Install Dependencies and pynmfk
        run: |
          conda info
          conda list
          conda install mpi4py
          python setup.py install
      
      - name: Run Tests
        run: |
          cd tests && ./test.sh
      
        env:
          OMPI_ALLOW_RUN_AS_ROOT: '1'
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: '1'